[package]
name = "multiplayer-connect-4-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.32.0", features = ["full"]}
connect_4 = {path="./connect_4"}
rand = "0.8.5"
